import httpx, fitz, concurrent.futures as cf
H={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0'}
urls = [
# BnD operators
"https://www.aggdoors.com.au/wp-content/uploads/2016/08/user-manual-bd-controll-a-door-4.pdf",
"https://ardentgaragedoors.com.au/wp-content/uploads/2020/04/Controll-A-Door-S-Panel-Pro-Manual.pdf",
"https://waverleygaragedoors.com.au/instruction-manuals/B&D%20CAD-P.pdf",
"https://waverleygaragedoors.com.au/instruction-manuals/B&D%20CAD.pdf",
"https://wrengineering.com.au/wp-content/uploads/2023/12/Controll-A-Door-Prodigy-Home-Owners-Manual-Jan-2015.pdf",
"https://ardentgaragedoors.com.au/wp-content/uploads/2020/04/Controll-A-Door-Power-Drive-and-Roll-A-Pro-Manual.pdf",
"https://motepro.com.au/Manuals/BND/Roller/cadr.pdf",
"https://motepro.com.au/Manuals/BND/Roller/cad5.pdf",
"https://wholesalegaragedoors.com.au/wp-content/uploads/2022/07/BnD-Doors-Australia-Secure-SDO-6-Installation-Manual.pdf",
"https://ardentgaragedoors.com.au/wp-content/uploads/2020/04/Controll-A-Door-Advance-Manual.pdf",
"https://admin.bnd.com.au/media/kvxfl3uy/160426_03-gdo-10-online-installation-manual.pdf",
"https://admin.bnd.com.au/media/dhjjoknd/161083_01-smartpro_smart_secure-online-installation-manual.pdf",
"https://admin.bnd.com.au/media/dexp2l4u/161060_05-panelmax-sdo-8v3-online-installation-manual.pdf",
"https://admin.bnd.com.au/media/crjlaqaa/161074_02-auto-lock-kit-gdl-200v2-sdo-installation-manual.pdf",
"https://admin.bnd.com.au/media/wj4mjmps/bd-smart-pro-opener-installation-guide-manual.pdf",
"https://admin.bnd.com.au/media/2b5isqvs/160485_01-online-quick-operation-guide-gdo-12.pdf",
"https://admin.bnd.com.au/media/ek2nezyl/161076_01-bd_quick-operation-guide-sdo-autolock.pdf",
"https://admin.bnd.com.au/media/l1ldtwhl/161082_00-online-quick-setup-guide-rdo-1-1.pdf",
"https://admin.bnd.com.au/media/ndifiiur/161081_00-online-quick-operation-guide-sdo-8.pdf",
"https://admin.bnd.com.au/media/vr4ckkdw/161068_01-b-d_quick-operation-guide.pdf",
"https://admin.bnd.com.au/media/foagrusx/bd_remote_compatibility_table_oct23.pdf",
# BnD doors
"https://www.bestsheds.com.au/wp-content/uploads/2020/08/BND_Firmadoor-Series-1_Rev6OCT16-1.pdf",
"https://admin.bnd.com.au/media/otvgbh1h/bd_panelift_rev4oct12.pdf",
"https://www.bestsheds.com.au/wp-content/uploads/2020/08/BD_Firmadoor-Series-2_Industrial_Rev5_Apr11.pdf",
"https://admin.bnd.com.au/media/uugh5tlh/165001_12_paneliftpft_pfi_installation-manual.pdf",
"https://automaticgaragesolutions.com.au/wp-content/uploads/2023/07/BD-Sectional-Panelift-B.pdf",
"https://admin.bnd.com.au/media/im4bstpz/165002_05_paneliftb_installation-manual.pdf",
"https://admin.bnd.com.au/media/nrhf5xiz/165007_10-series-2-installation-instructions.pdf",
"https://admin.bnd.com.au/media/ujjbjah0/165008_04_flushmount-designer-door_installation-manual.pdf",
"https://admin.bnd.com.au/media/tkchvh1t/165036_00-flex-a-door-installation-manual.pdf",
"https://admin.bnd.com.au/media/gsijmods/165023_02-esy-shutter-installation-manual.pdf",
"https://admin.bnd.com.au/media/daebnykw/165019_07-roll_a_door-series-3-installation-manual.pdf",
"https://admin.bnd.com.au/media/dr2dqwjy/165024_02-stormshield-installation-instructions.pdf",
"https://admin.bnd.com.au/media/hn2lbv5d/165100_15_roll-a-door_s1_plus-windlock.pdf",
"https://admin.bnd.com.au/media/nd0igbnz/bampd_firmapanel_rev5_apr11.pdf",
"https://admin.bnd.com.au/media/tc3humeh/bampd_panelmasta_rev4_apr11.pdf",
"https://admin.bnd.com.au/media/gdffarvj/bd_cedarpanel_rev1_jun11.pdf",
"https://admin.bnd.com.au/media/qhakkvdm/165005_08_designadoor-p7-industrial_installation-manual.pdf",
"https://admin.bnd.com.au/media/blub21ae/b-d_ras_envirashutter_rev3oct16.pdf",
"https://admin.bnd.com.au/media/2qelfkff/165105_05-residential-rolling-doors-jan25.pdf",
"https://admin.bnd.com.au/media/dr5bvbyv/165111_03-industrial-commercial-shutters-pg.pdf",
"https://admin.bnd.com.au/media/ku4pvs5k/165129_03-industrial-rolling-doors-jan25.pdf",
"https://admin.bnd.com.au/media/tcmdyrq5/165104_05-residential-sectional-digital-version.pdf",
"https://admin.bnd.com.au/media/qjbhaew3/165119_00-premium-and-speciality-doors-pg.pdf",
# Centurion
"https://www.cgdoors.com.au/wp-content/uploads/2021/10/RDO-10B-Instruction-Manual.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2020/04/8002-0011-05R-SDO-4-Instruction-Manual-English-2-buttons-for-Pro-800-RoHS-V1.2.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2022/02/Centurion-Roller-Door-Opener-RDO10C-User-Manual.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2022/02/Centurion-Garage-Door-Opener-Installation-Instructions.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2016/11/G4-Sectional-Door-Home-Owners-Manual-May-2018.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2024/02/Home-Owner-Manual-Quick-Fit-SD_RD20240209-1.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2016/11/Avanti-Sectional-Door-Opener-%E2%80%93-Owners-Manual.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2016/11/RDO10A-Roller-Door-Opener-%E2%80%93-Owners-Manual.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2020/02/12.3-New-Style-Digital-Avanti-Opener-Remote-Instructions-.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2020/02/SDO2-Coding-Instructions-004-2.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2022/02/RDO10A-Remote-Programming1.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2022/02/Wifi-Install-Instructions.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2022/06/GLD-RDO-Manual-114A5187B.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2022/10/SDO10-Coding-Instructions.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2024/12/Home-Owner-Manual-RD_RD20241211.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2024/12/Home-Owner-Manual-SD_RD20241211.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2016/11/Quick-Fit-Sectional-Door-Home-Owners-Manual-May-2018.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2016/11/Roller-Door-Home-Owners-Manual-May-2018.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2016/11/C2-Safe-Cyclonic-Door-User-Guide.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2016/11/Cyclonic-Garage-Doors-V4.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2017/11/Centurion-Roller-door-Brochure-6-pages-WEB.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2019/02/Sectional-Doors-Brochure-QLD_spreads.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2018/11/Timba-Look-Brochure_PDF-1.pdf",
"https://www.cgdoors.com.au/wp-content/uploads/2017/09/QuickFit-Sectional-Doors-Flyer-QLD-NSW-VIC-SA.pdf",
# Gliderol AU
"https://www.gliderol.com.au/wp-content/uploads/2025/02/GTS-Optima-Owners-Manual-amp-Install-Instructions.pdf",
"https://www.gliderol.com.au/wp-content/uploads/2025/02/GTS2000-Owners-Manual-V1-Board.pdf",
"https://www.gliderol.com.au/wp-content/uploads/2025/02/GTS2000-Owners-Manual-V2-Board.pdf",
"https://www.gliderol.com.au/wp-content/uploads/2025/02/GTS2000-Owners-Manual-amp-Install-Instructions.pdf",
"https://www.gliderol.com.au/wp-content/uploads/2025/02/Gliderol-Genesis-Series-Manual-V4.pdf",
"https://www.gliderol.com.au/wp-content/uploads/2025/02/Industrial-amp-Large-Residential-Series-B-Roller-Door-Install-Manual.pdf",
"https://www.gliderol.com.au/wp-content/uploads/2025/02/Residential-Series-A-Roller-Door-Install-Manual.pdf",
"https://www.gliderol.com.au/wp-content/uploads/2025/02/Safe-T-Glide-amp-Insul-Glide-Install-Instructions.pdf",
"https://www.gliderol.com.au/wp-content/uploads/2025/02/g-control-box-manual.pdf",
"https://www.gliderol.com.au/wp-content/uploads/2025/03/PF4-AUCBGID-10-Manual.pdf",
"https://www.gliderol.com.au/wp-content/uploads/2025/08/Gliderol-Rollamatic-GEN-II-User-Manual-1.pdf",
"https://www.gliderol.com.au/wp-content/uploads/2025/09/Panel-Glide-Installation-Manual.pdf",
"https://www.gliderol.com.au/wp-content/uploads/2025/02/Panel-Glide-Sectional-Overhead-Door-Install-Manual.pdf",
# Gliderol UK
"https://www.gliderol.co.uk/downloads/6621601b6b597737Single_Skin_Installation_Instructions_(Manual).pdf",
"https://www.gliderol.co.uk/downloads/662235f0e76ad490Gliderol_Insulated_Roller_Door_installation_instructions.pdf",
"https://www.gliderol.co.uk/downloads/6626a5271bd1c915B_series_industrial_door_installation_instructions.pdf",
"https://www.gliderol.co.uk/downloads/6623f71968060565Ro.in.One_Installation_Instructions_and_Owners_Manual.pdf",
"https://www.gliderol.co.uk/downloads/662e401ae0ea3595Gliderol_Garage_Doors_Framed_Canopy_fitting_instructions_V5.2.pdf",
"https://www.gliderol.co.uk/downloads/662e408a17954469Gliderol_Garage_Doors_Framed_Retractable_fitting_instructions_V6.1.pdf",
"https://www.gliderol.co.uk/downloads/686bb90c013b9236INSTALLATION_GUIDE_for_Gliderol_Sectional_Doors_v2.pdf",
"https://www.gliderol.co.uk/downloads/68b6bb0ddda9e578Roll_Smart_Book_compressed_(1).pdf",
"https://www.gliderol.co.uk/content/Mini_roll_single_skin_roller_installation_instructions.pdf",
# Steel-Line doors
"https://www.steel-line.com.au/wp-content/uploads/2024/11/Roller-Door-Owners-Manual_SL076A.pdf",
"https://www.steel-line.com.au/wp-content/uploads/2024/11/Sectional-Door-Installation-Incl-Inspiration-Revision-Jan-2021.pdf",
"https://www.steel-line.com.au/wp-content/uploads/2024/11/Sectional-Door-Manual-A3-single-page-view.pdf",
"https://www.steel-line.com.au/wp-content/uploads/2024/11/Series-A-Roller-Door-Installation.pdf",
"https://www.steel-line.com.au/wp-content/uploads/2024/11/Series-AA-Roller-Door-Installation-Guide.pdf",
"https://www.steel-line.com.au/wp-content/uploads/2024/11/Series-B-Roller-Door-Installation-Guide.pdf",
"https://www.steel-line.com.au/wp-content/uploads/2024/11/Series-C-Rated_Aluminium_-Door-Installation-Revision.pdf",
"https://www.steel-line.com.au/wp-content/uploads/2024/11/Wind-Brace-Door-Owners-Manual.pdf",
"https://www.steel-line.com.au/wp-content/uploads/2024/11/wind_brace_sectional_door_installation_guide.pdf",
"https://www.steel-line.com.au/wp-content/uploads/2024/11/no_brace_wind_rated_sectional_door_installation_guide.pdf",
# Steel-Line operators
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/installation_manual_sd800-v8-0820.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/installation_manual_rd800-v2-1219.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/installation_manual_sd1200-v2-0919.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/installation_manual_rd1200-v2-0520.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/ol6.5_sectional_garage_door_opener_-_users_manual.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/roller_door_operator.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/sd1000_pro_installation_instructions_and_user_guide.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/sd1000_std_installation_instructions_and_user_guide.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/rd1000_std_rd1000_pro_installation_instructions_and_user_guide.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/installation_manual_sprint800sd-v5-1219.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/installation_manual_sprint1200rd-v1-1219.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/installation_manual_sr1000-v1-0220.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/installation_manual_sr1300-v2-0520.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/sr60_roller_door_opener_owners_manual.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/rd11_installation_instruction_and_owners_manual.pdf",
"https://www.steel-lineautomation.com.au/uploads/7/2/0/3/7203835/multi_drive_1500_pro_installation_instructions_and_user_guide.pdf",
# Sanwa
"https://www.sanwa-ss.co.jp/english/files/pdf/shutters_and_shutter_related_products.pdf",
"https://www.sanwa-ss.co.jp/english/files/pdf/window_shutters.pdf",
"https://www.sanwa-ss.co.jp/english/files/Pas/1_S_ShutterRelated_Products.pdf",
"https://www.sun-metal.com/filesdirectserver/itp1/z_itp_05032024h8me/QSCatalog2014z-z236866821644.pdf",
]
def check(u):
    try:
        d=httpx.get(u,follow_redirects=True,timeout=45,headers=H,verify=False).content
        if d[:1024].find(b'%PDF')>=0 and b'%%EOF' in d[-3072:] and len(d)>40000:
            doc=fitz.open(stream=d,filetype='pdf'); n=doc.page_count; doc.close()
            return (u,'OK',n)
        return (u,'BAD',len(d))
    except Exception as e:
        return (u,'ERR',str(e)[:60])
with cf.ThreadPoolExecutor(max_workers=12) as ex:
    res=list(ex.map(check,urls))
for u,s,n in res:
    print(s, n, u)
print('TOTAL OK', sum(1 for _,s,_ in res if s=='OK'),'/',len(urls))
