/**
 * DoorDrawings Component
 * Combined view for all door drawings with export functionality
 *
 * Tabs:
 *  - Door Preview: SVG visual rendering for quick reference
 *  - Shop Drawing: production CAD drawing (PDF generated by backend
 *    ezdxf pipeline). Falls back to legacy SVG framing+elevation when
 *    no savedQuoteId is provided (admin DoorConfigurator before save).
 */

import { useState, useRef, useEffect } from 'react'
import DoorPreview from './DoorPreview'
import FramingDrawing from './FramingDrawing'
import SideElevationDrawing from './SideElevationDrawing'
import { exportAsSVG, exportAsPNG, exportAsPDF, printDrawing, exportDrawingPackage, getSvgFromRef } from '../utils/drawingExport'
import { doorConfigApi } from '../api/client'
import { savedQuotesApi } from '../api/customerClient'
import { extrasFromConfig, extrasFromLineItems } from '../utils/doorExtras'

const TABS = [
  { id: 'preview', label: 'Door Preview', icon: '\u{1F6AA}' },
  { id: 'shop_drawing', label: 'Shop Drawing', icon: '\u{1F4D0}' },
]

function DoorDrawings({
  doorConfig = {},
  showExport = true,
  defaultTab = 'preview',
  lineItems = null,
  extras: extrasProp = null,
  savedQuoteId = null,    // when set, the Shop Drawing tab uses the backend PDF endpoint
}) {
  // Resolve the optional-extras list for the framing drawing:
  //   1. explicit `extras` prop wins
  //   2. else derive from BC line items if provided
  //   3. else derive from the live doorConfig selections
  const resolvedExtras = Array.isArray(extrasProp)
    ? extrasProp
    : (Array.isArray(lineItems) && lineItems.length > 0
      ? extrasFromLineItems(lineItems)
      : extrasFromConfig(doorConfig))
  const [activeTab, setActiveTab] = useState(defaultTab)
  const [exportFormat, setExportFormat] = useState('pdf')
  const [geometry, setGeometry] = useState(null)
  const [geometryLoading, setGeometryLoading] = useState(false)
  const [geometryError, setGeometryError] = useState(null)

  // Backend shop drawing PDF state
  const [shopPdfUrl, setShopPdfUrl] = useState(null)
  const [shopPdfLoading, setShopPdfLoading] = useState(false)
  const [shopPdfError, setShopPdfError] = useState(null)

  // Refs for each drawing
  const previewRef = useRef(null)
  const framingRef = useRef(null)
  const elevationRef = useRef(null)

  // Extract door configuration with defaults
  const {
    doorWidth = 96,
    doorHeight = 84,
    panelColor = 'WHITE',
    panelDesign = 'SHXL',
    windowInsert = null,
    windowPositions = [],
    windowSection = 1,
    windowQty = 0,
    windowFrameColor = 'MATCH',
    hasInserts = false,
    glassColor = 'CLEAR',
    doorType = 'residential',
    doorSeries = 'KANATA',
    trackRadius = '15',
    trackThickness = '2',
    liftType: configLiftType = null,
    highLiftInches = null,
    trackMount = 'bracket',
    springCount = null,
    glassPocketsPerSection = null,
  } = doorConfig

  // Convert string values
  const widthInches = parseInt(doorWidth) || 96
  const heightInches = parseInt(doorHeight) || 84
  const radius = parseInt(trackRadius) || 15
  const trackSize = parseInt(trackThickness) || 2

  // Use config-provided lift type, or derive from track settings as fallback
  const liftType = configLiftType || (radius === 12 ? 'low_headroom' : 'standard')

  // Derive frame type from door type
  const frameType = doorType === 'residential' ? 'wood' : 'steel'

  // Fetch geometry from backend when relevant config changes
  useEffect(() => {
    const fetchGeometry = async () => {
      setGeometryLoading(true)
      setGeometryError(null)
      try {
        const widthFeet = Math.floor(widthInches / 12)
        const widthRemainder = widthInches % 12
        const heightFeet = Math.floor(heightInches / 12)
        const heightRemainder = heightInches % 12

        const resp = await doorConfigApi.getShopDrawingGeometry({
          widthFeet,
          widthInches: widthRemainder,
          heightFeet,
          heightInches: heightRemainder,
          trackSize,
          trackRadius: radius,
          liftType,
          highLiftInches: liftType === 'high_lift' ? (highLiftInches || 0) : 0,
          mountType: trackMount || 'bracket',
          frameType,
          doorType,
        })
        setGeometry(resp.data)
      } catch (err) {
        console.error('Failed to fetch shop drawing geometry:', err)
        setGeometryError(err.message || 'Failed to load geometry')
      } finally {
        setGeometryLoading(false)
      }
    }

    fetchGeometry()
  }, [widthInches, heightInches, trackSize, radius, liftType, highLiftInches, trackMount, frameType, doorType])

  // Lazy-load the backend shop drawing PDF when the tab opens
  useEffect(() => {
    if (activeTab !== 'shop_drawing' || !savedQuoteId) return
    if (shopPdfUrl || shopPdfLoading) return
    let cancelled = false
    const load = async () => {
      setShopPdfLoading(true)
      setShopPdfError(null)
      try {
        const resp = await savedQuotesApi.framingDrawing(savedQuoteId, { fmt: 'pdf' })
        if (cancelled) return
        const url = URL.createObjectURL(new Blob([resp.data], { type: 'application/pdf' }))
        setShopPdfUrl(url)
      } catch (err) {
        if (!cancelled) {
          setShopPdfError(err?.response?.data?.detail || err.message || 'Failed to load shop drawing')
        }
      } finally {
        if (!cancelled) setShopPdfLoading(false)
      }
    }
    load()
    return () => { cancelled = true }
  }, [activeTab, savedQuoteId, shopPdfUrl, shopPdfLoading])

  // Invalidate cached PDF when key config fields change
  useEffect(() => {
    if (shopPdfUrl) {
      URL.revokeObjectURL(shopPdfUrl)
      setShopPdfUrl(null)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [savedQuoteId, widthInches, heightInches, panelDesign, panelColor, doorSeries, liftType, highLiftInches, trackRadius])

  // Cleanup blob URL on unmount
  useEffect(() => () => {
    if (shopPdfUrl) URL.revokeObjectURL(shopPdfUrl)
  }, [shopPdfUrl])

  const downloadShopDrawing = async (fmt) => {
    if (!savedQuoteId) return
    try {
      const resp = await savedQuotesApi.framingDrawing(savedQuoteId, { fmt })
      const blob = new Blob([resp.data], {
        type: fmt === 'dxf' ? 'application/dxf' : 'application/pdf',
      })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `framing-drawing-${doorSeries}-${widthInches}x${heightInches}.${fmt}`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (err) {
      alert(err?.response?.data?.detail || err.message || 'Failed to download')
    }
  }

  // Handle export — only the SVG-rendered tabs (Preview + the SVG fallback in
  // Shop Drawing when no savedQuoteId). When a savedQuoteId is set, the
  // Shop Drawing tab uses dedicated Download PDF/DXF buttons instead.
  const handleExport = () => {
    let ref, filename
    if (activeTab === 'preview') {
      ref = previewRef
      filename = `door-preview-${widthInches}x${heightInches}`
    } else if (activeTab === 'shop_drawing' && !savedQuoteId) {
      ref = framingRef
      filename = `framing-drawing-${widthInches}x${heightInches}`
    } else {
      return
    }

    const svg = getSvgFromRef(ref)
    if (!svg) {
      alert('Drawing not available for export')
      return
    }

    switch (exportFormat) {
      case 'svg':
        exportAsSVG(svg, `${filename}.svg`)
        break
      case 'png':
        exportAsPNG(svg, `${filename}.png`, 2)
        break
      case 'pdf':
        exportAsPDF(svg, `${filename}.pdf`, `${doorSeries} ${Math.floor(widthInches / 12)}' x ${Math.floor(heightInches / 12)}'`, { vector: activeTab !== 'preview' })
        break
      case 'print':
        printDrawing(svg, `Door Drawing - ${doorSeries}`)
        break
      default:
        break
    }
  }

  // Handle export all
  const handleExportAll = () => {
    const drawings = [
      { element: getSvgFromRef(previewRef), title: 'Door Preview' },
      { element: getSvgFromRef(framingRef), title: 'Framing Drawing' },
      { element: getSvgFromRef(elevationRef), title: 'Side Elevation' },
    ].filter(d => d.element)

    if (drawings.length === 0) {
      alert('No drawings available for export')
      return
    }

    exportDrawingPackage(drawings, {
      series: doorSeries,
      width: Math.floor(widthInches / 12),
      height: Math.floor(heightInches / 12),
      color: panelColor,
    })
  }

  return (
    <div className="door-drawings bg-white rounded-lg shadow-sm border border-gray-200">
      {/* Tab Navigation */}
      <div className="border-b border-gray-200">
        <div className="flex items-center justify-between px-4">
          <nav className="flex space-x-4" aria-label="Tabs">
            {TABS.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`py-3 px-1 border-b-2 font-medium text-sm whitespace-nowrap ${
                  activeTab === tab.id
                    ? 'border-odc-500 text-odc-600'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                }`}
              >
                <span className="mr-1">{tab.icon}</span>
                {tab.label}
              </button>
            ))}
          </nav>

          {/* Export Controls */}
          {showExport && (
            <div className="flex items-center space-x-2 py-2">
              <select
                value={exportFormat}
                onChange={(e) => setExportFormat(e.target.value)}
                className="text-sm border border-gray-300 rounded px-2 py-1"
              >
                <option value="pdf">PDF</option>
                <option value="svg">SVG</option>
                <option value="png">PNG</option>
                <option value="print">Print</option>
              </select>
              <button
                onClick={handleExport}
                className="px-3 py-1 text-sm bg-odc-600 text-white rounded hover:bg-odc-700"
              >
                Export
              </button>
              <button
                onClick={handleExportAll}
                className="px-3 py-1 text-sm bg-gray-600 text-white rounded hover:bg-gray-700"
                title="Export all drawings as a package"
              >
                Export All
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Drawing Area */}
      <div className="p-4">
        {/* Door Preview Tab */}
        <div ref={previewRef} className={activeTab === 'preview' ? 'block' : 'hidden'}>
          <div className="flex flex-col md:flex-row items-start gap-6">
            <div className="flex-shrink-0">
              <DoorPreview
                width={widthInches}
                height={heightInches}
                color={panelColor}
                panelDesign={panelDesign}
                windowInsert={windowInsert}
                windowPositions={windowPositions}
                windowSection={windowSection}
                windowQty={windowQty}
                windowFrameColor={windowFrameColor}
                hasInserts={hasInserts}
                glassColor={glassColor}
                doorType={doorType}
                doorSeries={doorSeries}
                showDimensions={true}
                scale={1}
              />
            </div>
            <div className="flex-grow">
              <h3 className="text-lg font-medium text-gray-900 mb-3">Door Specifications</h3>
              <dl className="grid grid-cols-2 gap-2 text-sm">
                <dt className="text-gray-500">Series:</dt>
                <dd className="font-medium">{doorSeries}</dd>
                <dt className="text-gray-500">Size:</dt>
                <dd className="font-medium">{Math.floor(widthInches / 12)}' x {Math.floor(heightInches / 12)}'</dd>
                <dt className="text-gray-500">Color:</dt>
                <dd className="font-medium">{panelColor.replace(/_/g, ' ')}</dd>
                <dt className="text-gray-500">Panel Design:</dt>
                <dd className="font-medium">{panelDesign}</dd>
                <dt className="text-gray-500">Windows:</dt>
                <dd className="font-medium">{windowInsert && windowInsert !== 'NONE' ? `Yes (Section ${windowSection})` : 'None'}</dd>
                <dt className="text-gray-500">Track:</dt>
                <dd className="font-medium">{trackSize}" / {radius}" radius</dd>
              </dl>
            </div>
          </div>
        </div>

        {/* Shop Drawing Tab — backend-rendered PDF when savedQuoteId set,
             else legacy SVG framing + elevation as fallback */}
        <div className={activeTab === 'shop_drawing' ? 'block' : 'hidden'}>
          {savedQuoteId ? (
            <div>
              <div className="flex flex-wrap items-center gap-3 mb-3">
                <button
                  onClick={() => downloadShopDrawing('pdf')}
                  className="px-4 py-2 text-sm font-medium bg-odc-600 text-white rounded hover:bg-odc-700"
                >
                  Download PDF
                </button>
                <button
                  onClick={() => downloadShopDrawing('dxf')}
                  className="px-4 py-2 text-sm font-medium bg-gray-700 text-white rounded hover:bg-gray-800"
                  title="DXF for opening in CAD software"
                >
                  Download DXF
                </button>
                <span className="text-xs text-gray-500">
                  Includes front + side elevations, plan view, panel profile, optional extras checklist, and title block.
                </span>
              </div>

              {shopPdfLoading && (
                <div className="text-center py-12 text-gray-500">
                  Generating shop drawing…
                </div>
              )}
              {shopPdfError && !shopPdfLoading && (
                <div className="p-3 bg-red-50 border border-red-200 rounded text-sm text-red-700">
                  Could not load shop drawing: {shopPdfError}
                </div>
              )}
              {shopPdfUrl && !shopPdfLoading && (
                <div className="border border-gray-300 rounded">
                  <iframe
                    src={shopPdfUrl}
                    title="Shop Drawing PDF"
                    style={{ width: '100%', height: '70vh', minHeight: 500, border: 0 }}
                  />
                </div>
              )}
            </div>
          ) : (
            <div>
              <div className="p-3 mb-4 bg-amber-50 border border-amber-200 rounded text-sm text-amber-800">
                <strong>Heads up:</strong> save this configuration as a quote to access the
                full production shop drawing (PDF/DXF). Drawings below are an in-browser
                preview only.
              </div>
              <div ref={framingRef} className="mb-6">
                <h4 className="text-sm font-semibold text-gray-700 mb-2">Framing Preview</h4>
                <div className="overflow-x-auto">
                  {geometryLoading && (
                    <div className="text-center py-8 text-gray-500">Loading geometry…</div>
                  )}
                  {geometryError && !geometry && (
                    <div className="text-center py-8 text-red-500">Error loading geometry: {geometryError}</div>
                  )}
                  <FramingDrawing
                    width={widthInches}
                    height={heightInches}
                    trackRadius={radius}
                    trackSize={trackSize}
                    liftType={liftType}
                    geometry={geometry}
                    doorSeries={doorSeries}
                    doorType={doorType}
                    frameType={frameType}
                    mountType={trackMount || 'bracket'}
                    scale={0.6}
                    title={`FRAMING DRAWING - ${doorSeries}`}
                    springCount={springCount}
                    extras={resolvedExtras}
                    glassPocketsPerSection={glassPocketsPerSection}
                  />
                </div>
              </div>
              <div ref={elevationRef}>
                <h4 className="text-sm font-semibold text-gray-700 mb-2">Side Elevation Preview</h4>
                <div className="overflow-x-auto">
                  <SideElevationDrawing
                    width={widthInches}
                    height={heightInches}
                    trackRadius={radius}
                    trackSize={trackSize}
                    liftType={liftType}
                    highLiftInches={highLiftInches}
                    geometry={geometry}
                    doorSeries={doorSeries}
                    doorType={doorType}
                    scale={0.6}
                    title={`SIDE ELEVATION - ${doorSeries}`}
                  />
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Quick Actions */}
      <div className="border-t border-gray-200 px-4 py-3 bg-gray-50 flex justify-between items-center">
        <div className="text-sm text-gray-500">
          {doorSeries} {Math.floor(widthInches / 12)}' x {Math.floor(heightInches / 12)}' - {panelColor.replace(/_/g, ' ')}
        </div>
        <div className="flex space-x-2">
          <button
            onClick={() => window.print()}
            className="text-sm text-gray-600 hover:text-gray-800"
          >
            Print Current View
          </button>
        </div>
      </div>
    </div>
  )
}

export default DoorDrawings
