"""
BC AI Agent - Main FastAPI Application
Phase 1: Email-based quote request parsing + Quote generation
"""

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, Response
from starlette.middleware.base import BaseHTTPMiddleware
import logging
from contextlib import asynccontextmanager

# Import API routers
from app.api import feedback, auth, email_connections, email_feedback, quotes, orders, analytics, door_configurator
from app.api import customer_auth, customer_portal, admin_customers, admin_quotes, inventory, production, production_tasks
from app.api import chat, quote_review, projects, install_referrals
from app.api import settings as settings_api
from app.api import catalog
from app.api import inventory_agent
from app.api import po_agent
from app.api import public
from app.api import email_agent
from app.api import metrics
from app.api import integrations
from app.api import pricing_diagnostic
from app.api import customer_team
from app.api import external_keys
from app.api import external_pricing
from app.api import external_quotes

# Import services
from app.services.scheduler_service import get_scheduler
from app.config import settings

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan events"""
    # Startup
    logger.info("=" * 80)
    logger.info("BC AI Agent starting up...")
    logger.info("Phase 1: Email quote parsing + Quote generation")
    logger.info("=" * 80)

    # TODO: Initialize database connection
    # TODO: Initialize BC API client
    # TODO: Initialize Graph API client
    # TODO: Initialize Anthropic client

    # Start scheduled email monitoring — only in ONE Gunicorn worker.
    # With -w 4, each worker runs lifespan independently. Use a file lock
    # so only the first worker starts the scheduler; the rest skip it.
    import os
    _scheduler_lock = "/tmp/bc_scheduler_lock"
    _owns_scheduler = False
    if settings.ENABLE_EMAIL_MONITORING:
        try:
            fd = os.open(_scheduler_lock, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            os.write(fd, str(os.getpid()).encode())
            os.close(fd)
            _owns_scheduler = True
            scheduler = get_scheduler()
            scheduler.start(email_check_interval_minutes=settings.EMAIL_CHECK_INTERVAL_MINUTES)
            logger.info(f"✓ Scheduler started in worker PID {os.getpid()} (every {settings.EMAIL_CHECK_INTERVAL_MINUTES} min)")
        except FileExistsError:
            logger.info(f"Scheduler already running in another worker — skipping in PID {os.getpid()}")
        except Exception as e:
            logger.error(f"Failed to start scheduler: {e}", exc_info=True)
    else:
        logger.info("Email monitoring disabled (ENABLE_EMAIL_MONITORING=False)")

    # Initial BC sales-order sync — only run in the worker that owns the
    # scheduler lock, so we don't hammer BC with 4× the API calls under
    # Gunicorn. Done as an `await` here because lifespan is already inside
    # the asyncio event loop (asyncio.run can't nest).
    if _owns_scheduler:
        try:
            from app.services.bc_sync_service import bc_sync_service
            from app.db.database import SessionLocal as _SessionLocal
            _db = _SessionLocal()
            try:
                _stats = await bc_sync_service.sync_open_sales_orders_fast(_db)
                logger.info(
                    f"✓ Initial sales-order sync: {_stats.get('orders_synced', 0)} new, "
                    f"{_stats.get('orders_updated', 0)} updated, "
                    f"{len(_stats.get('errors', []))} errors"
                )
            finally:
                _db.close()
        except Exception as _sync_err:
            logger.error(f"Initial sales-order sync failed (non-fatal): {_sync_err}", exc_info=True)

    yield

    # Shutdown
    logger.info("=" * 80)
    logger.info("BC AI Agent shutting down...")
    logger.info("=" * 80)

    # Stop background scheduler (only in the worker that owns it)
    if _owns_scheduler:
        try:
            scheduler = get_scheduler()
            scheduler.stop()
            logger.info("Scheduler stopped")
            os.unlink(_scheduler_lock)
        except Exception as e:
            logger.error(f"Error stopping scheduler: {e}", exc_info=True)

    # TODO: Close database connections


# Create FastAPI application
app = FastAPI(
    title="BC AI Agent",
    description="AI-powered Business Central automation for quote generation and business operations",
    version="0.1.0",
    lifespan=lifespan
)

# Request-ID propagation middleware (SQB-11)
#
# Reads the inbound `X-Request-ID` header — generated by Service.AI's
# Fastify request id — and echoes it back on the response. When the
# header is absent (direct admin calls, anonymous probes) a UUIDv4
# is generated. The id is also attached to `request.state.request_id`
# so route handlers can include it in log statements; one id traces
# the full chain web → Service.AI → BC AI Agent → BC OData.
class RequestIdMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        import uuid
        rid = request.headers.get("x-request-id") or str(uuid.uuid4())
        request.state.request_id = rid
        response = await call_next(request)
        response.headers["X-Request-ID"] = rid
        return response


# Public-path CORS middleware — allow any origin for /api/public/* (widget embeds)
class PublicCORSMiddleware(BaseHTTPMiddleware):
    """Open CORS for /api/public/ so the widget works from any embedding site."""
    async def dispatch(self, request: Request, call_next):
        if request.url.path.startswith("/api/public/"):
            origin = request.headers.get("origin", "*")
            if request.method == "OPTIONS":
                return Response(
                    status_code=200,
                    headers={
                        "Access-Control-Allow-Origin": origin,
                        "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
                        "Access-Control-Allow-Headers": "Content-Type",
                        "Access-Control-Max-Age": "86400",
                    },
                )
            response = await call_next(request)
            response.headers["Access-Control-Allow-Origin"] = origin
            response.headers["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
            response.headers["Access-Control-Allow-Headers"] = "Content-Type"
            return response
        return await call_next(request)

# CORS middleware — origins come from ALLOWED_ORIGINS env var
app.add_middleware(
    CORSMiddleware,
    allow_origins=[o.strip() for o in settings.ALLOWED_ORIGINS.split(",") if o.strip()],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Public CORS must be added AFTER CORSMiddleware (runs first in reverse order)
# so it intercepts /api/public/ requests before the restricted CORS middleware
app.add_middleware(PublicCORSMiddleware)

# Request-ID is the outermost middleware so every other layer (CORS,
# auth, routers) sees `request.state.request_id` populated. Add it
# LAST so it wraps everything else (Starlette middleware order is
# inverse-registration: last-added is the outermost wrapper).
app.add_middleware(RequestIdMiddleware)

# Include API routers
# Mounting authentication and email connection routers
logger.info(f"Including auth router: {auth.router.prefix}")
app.include_router(auth.router)
logger.info(f"Including email_connections router: {email_connections.router.prefix}")
app.include_router(email_connections.router)
logger.info(f"Including feedback router: {feedback.router.prefix}")
app.include_router(feedback.router)
logger.info(f"Including email_feedback router: {email_feedback.router.prefix}")
app.include_router(email_feedback.router)
logger.info(f"Including quotes router: {quotes.router.prefix}")
app.include_router(quotes.router)
logger.info(f"Including orders router: {orders.router.prefix}")
app.include_router(orders.router)
logger.info(f"Including analytics router: {analytics.router.prefix}")
app.include_router(analytics.router)
logger.info(f"Including door_configurator router: {door_configurator.router.prefix}")
app.include_router(door_configurator.router)

# Customer Portal routers
logger.info(f"Including customer_auth router: {customer_auth.router.prefix}")
app.include_router(customer_auth.router)
logger.info(f"Including customer_portal router: {customer_portal.router.prefix}")
app.include_router(customer_portal.router)

# Admin Customer Management router (customer portal accounts)
logger.info(f"Including admin_customers router: {admin_customers.router.prefix}")
app.include_router(admin_customers.router)

# External API keys (SQB-03) — admin-only management surface for the
# keys that gate /api/external/* (SQB-04/05).
logger.info(f"Including external_keys router: {external_keys.router.prefix}")
app.include_router(external_keys.router)
# External price-items (SQB-04) — Service.AI calls this for live pricing.
logger.info(f"Including external_pricing router: {external_pricing.router.prefix}")
app.include_router(external_pricing.router)
# External quote commit (SQB-05) — Service.AI calls this on quote send.
logger.info(f"Including external_quotes router: {external_quotes.router.prefix}")
app.include_router(external_quotes.router)

# Admin Quote Search router (global cross-customer quote lookup)
logger.info(f"Including admin_quotes router: {admin_quotes.router.prefix}")
app.include_router(admin_quotes.router)

# Inventory Management router
logger.info(f"Including inventory router: {inventory.router.prefix}")
app.include_router(inventory.router)

# Production Management router
logger.info(f"Including production router: {production.router.prefix}")
app.include_router(production.router)

# Production Tasks router (task completion for shop floor)
logger.info(f"Including production_tasks router: {production_tasks.router.prefix}")
app.include_router(production_tasks.router)

# AI Chat router
logger.info(f"Including chat router: {chat.router.prefix}")
app.include_router(chat.router)

# Quote Review router (configurator feedback loop)
logger.info(f"Including quote_review router: {quote_review.router.prefix}")
app.include_router(quote_review.router)

# Settings router (Spring Inventory, etc.)
logger.info(f"Including settings router: {settings_api.router.prefix}")
app.include_router(settings_api.router)

# Catalog Builder router (OPENDC)
logger.info(f"Including catalog router: {catalog.router.prefix}")
app.include_router(catalog.router)

# Inventory Agent router (OPENDC)
logger.info(f"Including inventory_agent router: {inventory_agent.router.prefix}")
app.include_router(inventory_agent.router)

# PO Agent router (OPENDC)
logger.info(f"Including po_agent router: {po_agent.router.prefix}")
app.include_router(po_agent.router)

# Project / Lot Manager router (customer portal)
logger.info(f"Including projects router: {projects.router.prefix}")
app.include_router(projects.router)

# Install Referrals routers (customer + admin)
logger.info(f"Including install_referrals customer router: {install_referrals.customer_router.prefix}")
app.include_router(install_referrals.customer_router)
logger.info(f"Including install_referrals admin router: {install_referrals.admin_router.prefix}")
app.include_router(install_referrals.admin_router)

# Weekly Email Agent router
logger.info(f"Including email_agent router: {email_agent.router.prefix}")
app.include_router(email_agent.router)

# Business Metrics router
logger.info(f"Including metrics router: {metrics.router.prefix}")
app.include_router(metrics.router)

# Integrations router (service-to-service — Donna PA, email agents)
logger.info(f"Including integrations router: {integrations.router.prefix}")
app.include_router(integrations.router)

# Public endpoints (no auth — widget quote requests)
logger.info(f"Including public router: {public.public_router.prefix}")
app.include_router(public.public_router)
logger.info(f"Including admin_leads router: {public.admin_leads_router.prefix}")
app.include_router(public.admin_leads_router)

# Pricing diagnostic (read-only — compare legacy margin vs BC Sales Price hierarchy)
logger.info(f"Including pricing_diagnostic router: {pricing_diagnostic.router.prefix}")
app.include_router(pricing_diagnostic.router)

# Customer-portal team management (customer admins manage their own users)
logger.info(f"Including customer_team router: {customer_team.router.prefix}")
app.include_router(customer_team.router)

logger.info(f"Total routes after including routers: {len(app.routes)}")


@app.get("/")
async def root():
    """Health check endpoint"""
    return {
        "status": "operational",
        "service": "BC AI Agent",
        "phase": "1 - Email Quote Parsing",
        "version": "0.1.0"
    }


@app.post("/test-register")
async def test_register():
    """Test endpoint to verify POST works"""
    return {"message": "Test endpoint works!"}


@app.get("/debug/routes")
async def debug_routes():
    """Debug endpoint to list all registered routes"""
    routes_list = []
    for route in app.routes:
        if hasattr(route, 'path'):
            routes_list.append({
                "path": route.path,
                "methods": list(getattr(route, 'methods', []))
            })
    return {"total_routes": len(routes_list), "routes": routes_list}


@app.get("/health")
async def health_check():
    """Detailed health check"""
    # Check scheduler status
    try:
        scheduler = get_scheduler()
        scheduler_status = scheduler.get_status()
        email_monitoring_status = "running" if scheduler_status['running'] else "stopped"
    except:
        email_monitoring_status = "error"

    # TODO: Check BC API connectivity
    # TODO: Check database connectivity
    # TODO: Check email service connectivity

    return {
        "status": "healthy",
        "services": {
            "api": "operational",
            "database": "operational",
            "bc_connection": "pending",
            "email_monitoring": email_monitoring_status,
            "ai_service": "operational"
        }
    }


@app.get("/api/scheduler/status")
async def scheduler_status():
    """Get scheduler status and job details"""
    try:
        scheduler = get_scheduler()
        status = scheduler.get_status()

        return {
            "success": True,
            "scheduler": status,
            "message": "Scheduler is running" if status['running'] else "Scheduler is stopped"
        }
    except Exception as e:
        logger.error(f"Error getting scheduler status: {e}")
        return JSONResponse(
            status_code=500,
            content={
                "success": False,
                "error": str(e)
            }
        )


# Error handlers
@app.exception_handler(Exception)
async def global_exception_handler(request, exc):
    """Global exception handler"""
    logger.error(f"Unhandled exception: {exc}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={
            "error": "Internal server error",
            "message": str(exc)
        }
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
        log_level="info"
    )

